#!/usr/bin/env bash
#
# install-hooks.sh — generates .git/hooks/pre-commit
#
# Called by `npm run prepare` (runs on `npm install`).
# The generated hook runs:
#   1. Beads sync (flush pending changes)
#   2. ESLint + tsc --noEmit on staged .ts/.tsx/.js/.jsx files
#   3. cargo clippy on staged server/**/*.rs or server/Cargo.toml
#
# Skip all checks with: git commit --no-verify

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"

# For worktrees, hooks live in the common git dir
HOOKS_DIR="$(git rev-parse --git-common-dir)/hooks"
mkdir -p "$HOOKS_DIR"

HOOK_PATH="$HOOKS_DIR/pre-commit"

cat > "$HOOK_PATH" << 'HOOK_EOF'
#!/bin/sh
#
# Pre-commit hook: beads sync + lint + typecheck + clippy
# Auto-generated by scripts/install-hooks.sh — do not edit manually.
# Skip with: git commit --no-verify

# ── Beads sync ─────────────────────────────────────────────────────────
# Flush pending bd changes to .beads/issues.jsonl before commit.

if command -v bd >/dev/null 2>&1; then
  BEADS_DIR=""
  if git rev-parse --git-dir >/dev/null 2>&1; then
    if [ "$(git rev-parse --git-dir)" != "$(git rev-parse --git-common-dir)" ]; then
      MAIN_REPO_ROOT="$(dirname "$(git rev-parse --git-common-dir)")"
      if [ -d "$MAIN_REPO_ROOT/.beads" ]; then
        BEADS_DIR="$MAIN_REPO_ROOT/.beads"
      fi
    else
      if [ -d .beads ]; then
        BEADS_DIR=".beads"
      fi
    fi
  fi

  if [ -n "$BEADS_DIR" ]; then
    if ! bd export -o "$BEADS_DIR/issues.jsonl" >/dev/null 2>&1; then
      echo "Error: Failed to flush bd changes to JSONL" >&2
      echo "Run 'bd export -o .beads/issues.jsonl' manually to diagnose" >&2
      exit 1
    fi
    if [ -f "$BEADS_DIR/issues.jsonl" ]; then
      if [ "$(git rev-parse --git-dir)" = "$(git rev-parse --git-common-dir)" ]; then
        git add "$BEADS_DIR/issues.jsonl" 2>/dev/null || true
      fi
    fi
  fi
fi

# ── Resolve repo root ─────────────────────────────────────────────────

REPO_ROOT="$(git rev-parse --show-toplevel)"

# ── Collect staged files ───────────────────────────────────────────────

STAGED_FILES="$(git diff --cached --name-only --diff-filter=ACMR)"
if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

FRONTEND_FILES=""
RUST_FILES=""
HAS_CARGO_TOML=0

for f in $STAGED_FILES; do
  case "$f" in
    *.ts|*.tsx|*.js|*.jsx)
      FRONTEND_FILES="$FRONTEND_FILES $f"
      ;;
    server/*.rs)
      RUST_FILES="$RUST_FILES $f"
      ;;
    server/Cargo.toml)
      HAS_CARGO_TOML=1
      ;;
  esac
done

EXIT_CODE=0

# ── Frontend checks ───────────────────────────────────────────────────

if [ -n "$FRONTEND_FILES" ]; then
  if [ ! -d "$REPO_ROOT/node_modules" ]; then
    echo "Warning: node_modules not found, skipping frontend checks" >&2
    echo "  Run 'npm install' to enable pre-commit linting" >&2
  else
    echo "Running ESLint on staged files..."
    # shellcheck disable=SC2086
    if ! "$REPO_ROOT/node_modules/.bin/eslint" --max-warnings 0 $FRONTEND_FILES; then
      echo "ESLint failed. Fix errors or run: npx eslint --fix <files>" >&2
      EXIT_CODE=1
    fi

    echo "Running TypeScript type-check..."
    if ! "$REPO_ROOT/node_modules/.bin/tsc" --noEmit; then
      echo "TypeScript type-check failed." >&2
      EXIT_CODE=1
    fi
  fi
fi

# ── Rust checks ────────────────────────────────────────────────────────

if [ -n "$RUST_FILES" ] || [ "$HAS_CARGO_TOML" -eq 1 ]; then
  if ! command -v cargo >/dev/null 2>&1; then
    echo "Warning: cargo not found, skipping Rust checks" >&2
  else
    echo "Running cargo clippy on server..."
    if ! cargo clippy --manifest-path "$REPO_ROOT/server/Cargo.toml" -- -D warnings; then
      echo "Cargo clippy failed." >&2
      EXIT_CODE=1
    fi
  fi
fi

exit $EXIT_CODE
HOOK_EOF

chmod +x "$HOOK_PATH"
echo "Pre-commit hook installed at $HOOK_PATH"
